program_options:
  tray: auto                # Show tray icon when devices exist
  menu: flat                # Simple flat right-click menu
  automount: true           # Automatically mount removable devices
  notify: true              # Show libnotify notifications
  password_cache: 15        # Cache LUKS passwords for 15 minutes
  file_manager: thunar      # Replace with dolphin, nautilus, pcmanfm, etc.
  terminal: "ghostty -e"    # Terminal command (your Hyprland setup uses ghostty)
  password_prompt: builtin:gui  # Graphical password prompt for LUKS disks
  event_hook: false         # Disable external event hooks (can enable if needed)

notifications:
  timeout: 2                # Default notification timeout in seconds
  device_mounted: 5         # Show mount notifications
  device_unmounted: false   # Don’t spam on unmount
  device_added: false       # Don’t notify when device is plugged
  device_removed: false     # Don’t notify when device is unplugged
  device_unlocked: -1       # Use libnotify defaults
  device_locked: -1
  job_failed: -1            # Show failures with default timeout

quickmenu_actions: [mount, unmount, unlock, terminal, detach]

notification_actions:
  device_mounted: [browse]  # Show “Browse” button when mounted
  device_added: [mount]     # Show “Mount” when a new device is plugged

icon_names:
  media: [drive-removable-media, media-optical]
  browse: [document-open, folder-open]
  terminal: [terminal, ghostty, kitty]
  mount: [udiskie-mount]
  unmount: [udiskie-unmount]
  unlock: [udiskie-unlock]
  lock: [udiskie-lock]
  eject: [udiskie-eject, media-eject]
  detach: [udiskie-detach]
  delete: [udiskie-eject]
  quit: [application-exit]

device_config:
  # Ignore FAT boot partitions (common on Linux installs)
  - id_type: vfat
    automount: false
    ignore: true

  # Example: never automount NTFS drives
  - id_type: ntfs
    automount: false
    ignore: false

